server:
  port: 8083

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/team_management?currentSchema=audit}
    username: ${SPRING_DATASOURCE_USERNAME:team_user}
    password: ${SPRING_DATASOURCE_PASSWORD:team_password}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: audit

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
