create schema if not exists statistics;

create table statistics.player_stats_projection
(
    id                         bigint generated by default as identity primary key,
    player_id                  bigint                   not null,
    player_name_snapshot       varchar(100)             not null,
    season                     varchar(30)              not null,
    tournament_id              bigint                   not null,
    tournament_name_snapshot   varchar(100)             not null,
    appearances                integer default 0        not null,
    starts                     integer default 0        not null,
    goals                      integer default 0        not null,
    assists                    integer default 0        not null,
    goal_involvements          integer default 0        not null,
    updated_at                 timestamp with time zone not null,
    constraint uk_player_stats_player_season_tournament
        unique (player_id, season, tournament_id)
);

create index idx_player_stats_season_tournament
    on statistics.player_stats_projection (season, tournament_id);

create table statistics.match_player_appearance_projection
(
    id                         bigint generated by default as identity primary key,
    match_id                   bigint                   not null,
    player_id                  bigint                   not null,
    season                     varchar(30)              not null,
    tournament_id              bigint                   not null,
    appearance_count           integer default 0        not null,
    starter_count              integer default 0        not null,
    updated_at                 timestamp with time zone not null,
    constraint uk_match_player_appearance
        unique (match_id, player_id)
);

create index idx_match_player_appearance_match
    on statistics.match_player_appearance_projection (match_id);

create index idx_match_player_appearance_player
    on statistics.match_player_appearance_projection (player_id);

create table statistics.team_stats_projection
(
    id                         bigint generated by default as identity primary key,
    team_id                    bigint                   not null,
    team_name_snapshot         varchar(100)             not null,
    season                     varchar(30)              not null,
    tournament_id              bigint                   not null,
    tournament_name_snapshot   varchar(100)             not null,
    played                     integer default 0        not null,
    win                        integer default 0        not null,
    draw                       integer default 0        not null,
    lose                       integer default 0        not null,
    goals_for                  integer default 0        not null,
    goals_against              integer default 0        not null,
    goal_diff                  integer default 0        not null,
    points                     integer default 0        not null,
    rank_no                    integer,
    updated_at                 timestamp with time zone not null,
    constraint uk_team_stats_team_season_tournament
        unique (team_id, season, tournament_id),
    constraint ck_team_stats_projection_non_negative
        check (
            played >= 0
            and win >= 0
            and draw >= 0
            and lose >= 0
            and goals_for >= 0
            and goals_against >= 0
            and points >= 0
            and (
                rank_no is null
                or rank_no > 0
            )
        )
);

create index idx_team_stats_season_tournament
    on statistics.team_stats_projection (season, tournament_id);

create table statistics.leaderboard_projection
(
    id                         bigint generated by default as identity primary key,
    board_type                 varchar(30)              not null,
    season                     varchar(30)              not null,
    tournament_id              bigint                   not null,
    rank_no                    integer                  not null,
    entity_id                  bigint                   not null,
    entity_name_snapshot       varchar(100)             not null,
    metric_value               integer                  not null,
    updated_at                 timestamp with time zone not null,
    constraint uk_leaderboard_board_season_tournament_entity
        unique (board_type, season, tournament_id, entity_id)
);

create index idx_leaderboard_board_rank
    on statistics.leaderboard_projection (board_type, season, tournament_id, rank_no);

create table statistics.match_summary_projection
(
    id                          bigint generated by default as identity primary key,
    match_id                    bigint                   not null,
    tournament_id               bigint                   not null,
    tournament_name_snapshot    varchar(100)             not null,
    season_snapshot             varchar(30)              not null,
    match_time                  timestamp with time zone not null,
    opponent_team_name_snapshot varchar(100)             not null,
    home_away                   varchar(10)              not null,
    our_score                   integer                  not null,
    opponent_score              integer                  not null,
    match_status                varchar(20)              not null,
    finished                    boolean                  not null,
    updated_at                  timestamp with time zone not null,
    constraint uk_match_summary_match
        unique (match_id)
);

create index idx_match_summary_match_time
    on statistics.match_summary_projection (match_time);

create index idx_match_summary_tournament_time
    on statistics.match_summary_projection (tournament_id, match_time);

create table statistics.event_consume_record
(
    id            bigint generated by default as identity primary key,
    event_id      uuid                     not null,
    consumer_name varchar(100)             not null,
    consumed_at   timestamp with time zone not null,
    constraint uk_event_consume_record_event_consumer
        unique (event_id, consumer_name)
);

create index idx_event_consume_record_event_id
    on statistics.event_consume_record (event_id);
