server:
  port: 8084

spring:
  application:
    name: match-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/team_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: match
        format_sql: true

    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

services:
  team-service:
    base-url: ${TEAM_SERVICE_BASE_URL:http://localhost:8082}
  tournament-service:
    base-url: ${TOURNAMENT_SERVICE_BASE_URL:http://localhost:8085}

app:
  kafka:
    topics:
      match-events: match-service.match-events
