CREATE SCHEMA IF NOT EXISTS identity AUTHORIZATION team_user;
CREATE SCHEMA IF NOT EXISTS team AUTHORIZATION team_user;
CREATE SCHEMA IF NOT EXISTS tournament AUTHORIZATION team_user;
CREATE SCHEMA IF NOT EXISTS match AUTHORIZATION team_user;
CREATE SCHEMA IF NOT EXISTS statistics AUTHORIZATION team_user;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION team_user;

GRANT ALL PRIVILEGES ON SCHEMA identity TO team_user;
GRANT ALL PRIVILEGES ON SCHEMA team TO team_user;
GRANT ALL PRIVILEGES ON SCHEMA tournament TO team_user;
GRANT ALL PRIVILEGES ON SCHEMA match TO team_user;
GRANT ALL PRIVILEGES ON SCHEMA statistics TO team_user;
GRANT ALL PRIVILEGES ON SCHEMA audit TO team_user;
