server:
  port: 8085

spring:
  application:
    name: tournament-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/team_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: tournament
        format_sql: true

    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  kafka:
    topics:
      tournament-events: tournament-service.tournament-events
